dataset_path: floschne/marvl
dataset_name: default
dataset_kwargs:
  token: True
task: "marvl_ta"
test_split: ta
output_type: generate_until
doc_to_visual: !function utils.marvl_doc_to_visual
doc_to_text: !function utils.marvl_doc_to_text
doc_to_target: "label"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0
  
model_specific_prompt_kwargs:
  default:
    hypothesis_prompt: "Hypothesis: "
    
