dataset_path: afaji/cvqa
dataset_name: default
task : "cvqa_test"
group : "cvqa"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.cvqa_doc_to_visual
doc_to_text: !function utils.cvqa_doc_to_text
doc_to_target: !function utils.cvqa_doc_to_target
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False
process_results: !function utils.cvqa_process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0